# config.yaml
time_seed: 0
output_folder: "train_my_1d_batch_sample"

# 1d: my_1d, wiggle, matern, andrew, agw, 
# 2d: origin, axis
dataset: "my_1d"
remark: ""
condition_scale: 1
position_encode: True
position_encode_m: 2
var_scale: 10
# train
batch: 100
epochs: 40
flow_modules: '32-32-32-32-32'
cond_size: 1
lr: 1.0e-3
inputDim: 1
add_uniform: True
uniform_rate: 0.1
# eval
sample_count: 300
eval_data:
  count: 300